	DROP TABLE T_WEDDING_SALE PURGE;
	DROP SEQUENCE T_WEDDING_SALE_SEQ;	

	CREATE TABLE  T_WEDDING_SALE(
		NUM NUMBER(6,0) NOT NULL ENABLE, 
		NAME VARCHAR2(100) NOT NULL ENABLE, 
		PAYMENT NUMBER(6,0) NOT NULL ENABLE, 
		QUANTITY NUMBER(6,0) NOT NULL ENABLE, 
		EMAIL VARCHAR2(200) NOT NULL ENABLE, 
		CATEGORY VARCHAR2(100) NOT NULL ENABLE
	);

	SELECT * FROM T_WEDDING_SALE;
  	 
	CREATE SEQUENCE T_WEDDING_SALE_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;
	
	ALTER TABLE T_WEDDING_SALE ADD CONSTRAINT T_WEDDING_SALE_PK PRIMARY KEY(NUM);
	
	INSERT INTO T_WEDDING_SALE VALUES(T_WEDDING_SALE_SEQ.NEXTVAL,'GAS 커피',171000,19,'wastty@naver.com','gift_Food');
	INSERT INTO T_WEDDING_SALE VALUES(T_WEDDING_SALE_SEQ.NEXTVAL,'GAS 커피',99000,11,'wastty@naver.com','gift_Food');
	INSERT INTO T_WEDDING_SALE VALUES(T_WEDDING_SALE_SEQ.NEXTVAL,'GAS 커피',81000,9,'wastty@naver.com','gift_Food');
	INSERT INTO T_WEDDING_SALE VALUES(T_WEDDING_SALE_SEQ.NEXTVAL,'장미향 디퓨저',37500,15,'wastty@naver.com','gift_Useful');
	INSERT INTO T_WEDDING_SALE VALUES(T_WEDDING_SALE_SEQ.NEXTVAL,'조셉조셉도마',40000,1,'wastty@naver.com','registery');
	INSERT INTO T_WEDDING_SALE VALUES(T_WEDDING_SALE_SEQ.NEXTVAL,'아로마향 양초',25000,10,'wastty@naver.com','gift_Useful');
	INSERT INTO T_WEDDING_SALE VALUES(T_WEDDING_SALE_SEQ.NEXTVAL,'커플 컵',20000,5,'wastty@naver.com','gift_Kitchen');
	INSERT INTO T_WEDDING_SALE VALUES(T_WEDDING_SALE_SEQ.NEXTVAL,'기본형 소이캔들',20000,10,'wastty@naver.com','gift_Useful');
	
	INSERT INTO T_WEDDING_SALE VALUES(T_WEDDING_SALE_SEQ.NEXTVAL,'GAS 커피',171000,19,'seongkwon7000@gamil.com','gift_Food');
	INSERT INTO T_WEDDING_SALE VALUES(T_WEDDING_SALE_SEQ.NEXTVAL,'GAS 커피',99000,11,'seongkwon7000@gamil.com','gift_Food');
	INSERT INTO T_WEDDING_SALE VALUES(T_WEDDING_SALE_SEQ.NEXTVAL,'GAS 커피',81000,9,'seongkwon7000@gamil.com','gift_Food');
	INSERT INTO T_WEDDING_SALE VALUES(T_WEDDING_SALE_SEQ.NEXTVAL,'장미향 디퓨저',37500,15,'seongkwon7000@gamil.com','gift_Useful');
	INSERT INTO T_WEDDING_SALE VALUES(T_WEDDING_SALE_SEQ.NEXTVAL,'조셉조셉도마',40000,1,'seongkwon7000@gamil.com','registery');
	INSERT INTO T_WEDDING_SALE VALUES(T_WEDDING_SALE_SEQ.NEXTVAL,'아로마향 양초',25000,10,'seongkwon7000@gamil.com','gift_Useful');
	INSERT INTO T_WEDDING_SALE VALUES(T_WEDDING_SALE_SEQ.NEXTVAL,'커플 컵',20000,5,'seongkwon7000@gamil.com','gift_Kitchen');
	INSERT INTO T_WEDDING_SALE VALUES(T_WEDDING_SALE_SEQ.NEXTVAL,'기본형 소이캔들',20000,10,'seongkwon7000@gamil.com','gift_Useful');

