	DROP TABLE T_WEDDING_QANDA PURGE;
	DROP SEQUENCE T_WEDDING_QANDA_SEQ;	
	
	CREATE TABLE  T_WEDDING_QANDA(
		NUM NUMBER(6,0), 
		GROUPNUM NUMBER(6,0) NOT NULL ENABLE, 
		REPLYSEQ NUMBER(6,0) NOT NULL ENABLE, 
		REPLYLEVEL NUMBER(6,0) NOT NULL ENABLE, 
		VIEWCNT NUMBER(6,0) NOT NULL ENABLE, 
		TITLE VARCHAR2(200), 
		WRITER VARCHAR2(200), 
		CONTENTS VARCHAR2(200), 
		SAVEDATE DATE
	);
	
	SELECT * FROM T_WEDDING_QANDA;
  	 
	CREATE SEQUENCE T_WEDDING_QANDA_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;
	
	ALTER TABLE T_WEDDING_QANDA ADD CONSTRAINT T_WEDDING_QANDA_PK PRIMARY KEY(NUM);
	
	INSERT INTO T_WEDDING_QANDA VALUES(T_WEDDING_QANDA_SEQ.NEXTVAL,8,0,0,1,'자소서','ㅎㅎㅎ','자쫌..',sysdate);
	INSERT INTO T_WEDDING_QANDA VALUES(T_WEDDING_QANDA_SEQ.NEXTVAL,9,0,0,1,'자기소개서','자기','소개점',sysdate);
	INSERT INTO T_WEDDING_QANDA VALUES(T_WEDDING_QANDA_SEQ.NEXTVAL,10,0,0,1,'왕이달리다','넘어지면?','킹콩',sysdate);
	INSERT INTO T_WEDDING_QANDA VALUES(T_WEDDING_QANDA_SEQ.NEXTVAL,11,0,0,1,'뿌뿌뿌','빠빰','뿡뿡',sysdate);
	INSERT INTO T_WEDDING_QANDA VALUES(T_WEDDING_QANDA_SEQ.NEXTVAL,12,0,0,1,'수정해주는데','10만원','ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ',sysdate);
	INSERT INTO T_WEDDING_QANDA VALUES(T_WEDDING_QANDA_SEQ.NEXTVAL,13,0,0,1,'룰루','하하','네네',sysdate);
	INSERT INTO T_WEDDING_QANDA VALUES(T_WEDDING_QANDA_SEQ.NEXTVAL,14,0,0,1,'레릿고','아이','원더',sysdate);
	INSERT INTO T_WEDDING_QANDA VALUES(T_WEDDING_QANDA_SEQ.NEXTVAL,15,0,0,1,'스리라','아아앙','카',sysdate);
	INSERT INTO T_WEDDING_QANDA VALUES(T_WEDDING_QANDA_SEQ.NEXTVAL,16,0,0,1,'니노막시무스','카이저소제','쏘냐도르앤스파르타',sysdate);
	INSERT INTO T_WEDDING_QANDA VALUES(T_WEDDING_QANDA_SEQ.NEXTVAL,17,0,0,1,'씡긔방긔','하군','ㅋㅋㄷㅋㄷ',sysdate);
	INSERT INTO T_WEDDING_QANDA VALUES(T_WEDDING_QANDA_SEQ.NEXTVAL,18,0,0,1,'슛돌이능','뷰티풀','똥칼라파워',sysdate);
	INSERT INTO T_WEDDING_QANDA VALUES(T_WEDDING_QANDA_SEQ.NEXTVAL,19,0,0,1,'라랄라','내가','라라랄',sysdate);
	INSERT INTO T_WEDDING_QANDA VALUES(T_WEDDING_QANDA_SEQ.NEXTVAL,20,0,0,1,'369','369','1',sysdate);
	INSERT INTO T_WEDDING_QANDA VALUES(T_WEDDING_QANDA_SEQ.NEXTVAL,21,0,0,1,'그렇구나','니가그래서','그랫구나',sysdate);
	INSERT INTO T_WEDDING_QANDA VALUES(T_WEDDING_QANDA_SEQ.NEXTVAL,22,0,0,1,'ㅋㅋㅋ','가져다','쓰면된대용',sysdate);
	INSERT INTO T_WEDDING_QANDA VALUES(T_WEDDING_QANDA_SEQ.NEXTVAL,23,0,0,1,'으잉?','얼마나','어려운걸..',sysdate);
	INSERT INTO T_WEDDING_QANDA VALUES(T_WEDDING_QANDA_SEQ.NEXTVAL,24,0,0,1,'아','이게' ,'왜뜨지?',sysdate);
	INSERT INTO T_WEDDING_QANDA VALUES(T_WEDDING_QANDA_SEQ.NEXTVAL,25,0,0,1,'이상하다~','왜','안되지~?',sysdate);
	INSERT INTO T_WEDDING_QANDA VALUES(T_WEDDING_QANDA_SEQ.NEXTVAL,26,0,0,1,'어~','이상하다~','돼야되는데~?',sysdate);
	INSERT INTO T_WEDDING_QANDA VALUES(T_WEDDING_QANDA_SEQ.NEXTVAL,27,0,0,1,'ㅇ','ㅇ','ㅇ',sysdate);
	INSERT INTO T_WEDDING_QANDA VALUES(T_WEDDING_QANDA_SEQ.NEXTVAL,1,0,0,1,'AAA','AAA','AAA',sysdate);
	INSERT INTO T_WEDDING_QANDA VALUES(T_WEDDING_QANDA_SEQ.NEXTVAL,3,0,0,1,'다시다시','CCC','CCC',sysdate);
	INSERT INTO T_WEDDING_QANDA VALUES(T_WEDDING_QANDA_SEQ.NEXTVAL,4,0,0,1,'네번째 대표글','ㅁㄻㄹ','ㅁㄹ',sysdate);
	INSERT INTO T_WEDDING_QANDA VALUES(T_WEDDING_QANDA_SEQ.NEXTVAL,4,2,1,1,'네번째 첫 답글','','1111',sysdate);
	INSERT INTO T_WEDDING_QANDA VALUES(T_WEDDING_QANDA_SEQ.NEXTVAL,4,1,1,1,'네번째 2번 답글','','2222',sysdate);
	INSERT INTO T_WEDDING_QANDA VALUES(T_WEDDING_QANDA_SEQ.NEXTVAL,7,0,0,1,'ㅋㅋㅋㅋ','주딩','아아아아',sysdate);
	INSERT INTO T_WEDDING_QANDA VALUES(T_WEDDING_QANDA_SEQ.NEXTVAL,14,0,0,1,'fewafw','gawefgw','gragwr',sysdate);
	INSERT INTO T_WEDDING_QANDA VALUES(T_WEDDING_QANDA_SEQ.NEXTVAL,13,0,0,1,'한번더','나에게','질풍같은',sysdate);
	INSERT INTO T_WEDDING_QANDA VALUES(T_WEDDING_QANDA_SEQ.NEXTVAL,16,0,0,1,'잘가요','내사랑','이제보내줄께요~',sysdate);
	INSERT INTO T_WEDDING_QANDA VALUES(T_WEDDING_QANDA_SEQ.NEXTVAL,21,0,0,1,'fweaf','fweafawe','fweafwe',sysdate);
	INSERT INTO T_WEDDING_QANDA VALUES(T_WEDDING_QANDA_SEQ.NEXTVAL,24,0,0,1,'','','',sysdate);
	INSERT INTO T_WEDDING_QANDA VALUES(T_WEDDING_QANDA_SEQ.NEXTVAL,27,1,1,1,'','ㅇ','',sysdate);
	INSERT INTO T_WEDDING_QANDA VALUES(T_WEDDING_QANDA_SEQ.NEXTVAL,17,2,1,1,'라이언','ㅇ','라이언',sysdate);
	INSERT INTO T_WEDDING_QANDA VALUES(T_WEDDING_QANDA_SEQ.NEXTVAL,19,0,0,1,'안녕','준호야','ㅋㅋㅋㅋ',sysdate);
	INSERT INTO T_WEDDING_QANDA VALUES(T_WEDDING_QANDA_SEQ.NEXTVAL,20,0,0,1,'fawe','fewawef','wfaefwe',sysdate);
	INSERT INTO T_WEDDING_QANDA VALUES(T_WEDDING_QANDA_SEQ.NEXTVAL,27,1,1,1,'ㅗㅇㄱㄹ','ㅇ','ㅗㄱ옹ㄱ',sysdate);
	INSERT INTO T_WEDDING_QANDA VALUES(T_WEDDING_QANDA_SEQ.NEXTVAL,23,0,0,1,'ㅛㄷ4ㅛㅅ','ㄷㅅㄴㅅㄴ','ㅎㄷㄶㄴ',sysdate);
	
