	DROP TABLE T_WEDDING_REGISTRYFRIENDS PURGE;
	DROP SEQUENCE T_WEDDING_REGISTRYFRIENDS_SEQ;

	CREATE TABLE  T_WEDDING_REGISTRYFRIENDS(
		NUM NUMBER(6,0) NOT NULL ENABLE, 
		EMAIL VARCHAR2(300), 
		FNAME VARCHAR2(300), 
		FEMAIL VARCHAR2(300), 
		FPHONE VARCHAR2(15)
   	);
   	
   	SELECT * FROM T_WEDDING_REGISTRYFRIENDS;
  	 
	CREATE SEQUENCE T_WEDDING_REGISTRYFRIENDS_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;
	
	ALTER TABLE T_WEDDING_REGISTRYFRIENDS ADD CONSTRAINT T_WEDDING_REGISTRYFRIENDS_PK PRIMARY KEY(NUM);
	
	INSERT INTO T_WEDDING_REGISTRYFRIENDS 
	VALUES(T_WEDDING_REGISTRYFRIENDS_SEQ.NEXTVAL,'seongkwon7000@gmail.com','서희현','gm300643@hanmail.com','010-7358-1027');
	
	INSERT INTO T_WEDDING_REGISTRYFRIENDS 
	VALUES(T_WEDDING_REGISTRYFRIENDS_SEQ.NEXTVAL,'seongkwon7000@gmail.com','양기열','ykycome00@gmail.com','010-2708-0663');
	
	INSERT INTO T_WEDDING_REGISTRYFRIENDS 
	VALUES(T_WEDDING_REGISTRYFRIENDS_SEQ.NEXTVAL,'seongkwon7000@gmail.com','김태민','xoalszz123@naver.com','010-4339-9307');
	
	INSERT INTO T_WEDDING_REGISTRYFRIENDS 
	VALUES(T_WEDDING_REGISTRYFRIENDS_SEQ.NEXTVAL,'seongkwon7000@gmail.com','이지현','jihyun7608@naver.com','010-2586-7608');
	
	INSERT INTO T_WEDDING_REGISTRYFRIENDS 
	VALUES(T_WEDDING_REGISTRYFRIENDS_SEQ.NEXTVAL,'seongkwon7000@gmail.com','김정식','zxc7qwe@naver.com','010-9793-4966');
	
	INSERT INTO T_WEDDING_REGISTRYFRIENDS 
	VALUES(T_WEDDING_REGISTRYFRIENDS_SEQ.NEXTVAL,'seongkwon7000@gmail.com','송지원','thdwldnjs8799@naver.com','010-6256-8799');
	
	INSERT INTO T_WEDDING_REGISTRYFRIENDS 
	VALUES(T_WEDDING_REGISTRYFRIENDS_SEQ.NEXTVAL,'seongkwon7000@gmail.com','김다솜','ektha920@naver.com','010-7144-6376');
	
	INSERT INTO T_WEDDING_REGISTRYFRIENDS 
	VALUES(T_WEDDING_REGISTRYFRIENDS_SEQ.NEXTVAL,'seongkwon7000@gmail.com','안용민','326yongme@naver.com','010-6361-1127');
	
	INSERT INTO T_WEDDING_REGISTRYFRIENDS 
	VALUES(T_WEDDING_REGISTRYFRIENDS_SEQ.NEXTVAL,'seongkwon7000@gmail.com','남준호','jun3386@nate.com','010-2822-5541');
	
	INSERT INTO T_WEDDING_REGISTRYFRIENDS 
	VALUES(T_WEDDING_REGISTRYFRIENDS_SEQ.NEXTVAL,'seongkwon7000@gmail.com','이상현','mylesh21@naver.com','010-6540-4218');
	
	INSERT INTO T_WEDDING_REGISTRYFRIENDS 
	VALUES(T_WEDDING_REGISTRYFRIENDS_SEQ.NEXTVAL,'seongkwon7000@gmail.com','조태환','01062744133@naver.com','010-6275-4138');
	
	INSERT INTO T_WEDDING_REGISTRYFRIENDS 
	VALUES(T_WEDDING_REGISTRYFRIENDS_SEQ.NEXTVAL,'seongkwon7000@gmail.com','윤현종','wastty@naver.com','010-9448-5627');

	
	INSERT INTO T_WEDDING_REGISTRYFRIENDS 
	VALUES(T_WEDDING_REGISTRYFRIENDS_SEQ.NEXTVAL,'wastty@naver.com','서희현','gm300643@hanmail.com','010-7358-1027');
	
	INSERT INTO T_WEDDING_REGISTRYFRIENDS 
	VALUES(T_WEDDING_REGISTRYFRIENDS_SEQ.NEXTVAL,'wastty@naver.com','양기열','ykycome00@gmail.com','010-2708-0663');
	
	INSERT INTO T_WEDDING_REGISTRYFRIENDS 
	VALUES(T_WEDDING_REGISTRYFRIENDS_SEQ.NEXTVAL,'wastty@naver.com','김태민','xoalszz123@naver.com','010-4339-9307');
	
	INSERT INTO T_WEDDING_REGISTRYFRIENDS 
	VALUES(T_WEDDING_REGISTRYFRIENDS_SEQ.NEXTVAL,'wastty@naver.com','이지현','wlgus7608@naver.com','010-2586-7608');
	
	INSERT INTO T_WEDDING_REGISTRYFRIENDS 
	VALUES(T_WEDDING_REGISTRYFRIENDS_SEQ.NEXTVAL,'wastty@naver.com','김정식','zxc7qwe@naver.com','010-9793-4966');
	
	INSERT INTO T_WEDDING_REGISTRYFRIENDS 
	VALUES(T_WEDDING_REGISTRYFRIENDS_SEQ.NEXTVAL,'wastty@naver.com','송지원','thdwldnjs8799@naver.com','010-6256-8799');
	
	INSERT INTO T_WEDDING_REGISTRYFRIENDS 
	VALUES(T_WEDDING_REGISTRYFRIENDS_SEQ.NEXTVAL,'wastty@naver.com','김다솜','ektha920@naver.com','010-7144-6376');
	
	INSERT INTO T_WEDDING_REGISTRYFRIENDS 
	VALUES(T_WEDDING_REGISTRYFRIENDS_SEQ.NEXTVAL,'wastty@naver.com','안용민','326yongme@naver.com','010-6361-1127');
	
	INSERT INTO T_WEDDING_REGISTRYFRIENDS 
	VALUES(T_WEDDING_REGISTRYFRIENDS_SEQ.NEXTVAL,'wastty@naver.com','남준호','jun3386@nate.com','010-2822-5541');
	
	INSERT INTO T_WEDDING_REGISTRYFRIENDS 
	VALUES(T_WEDDING_REGISTRYFRIENDS_SEQ.NEXTVAL,'wastty@naver.com','이상현','mylesh21@naver.com','010-6540-4218');
	
	INSERT INTO T_WEDDING_REGISTRYFRIENDS 
	VALUES(T_WEDDING_REGISTRYFRIENDS_SEQ.NEXTVAL,'wastty@naver.com','조태환','01062744133@naver.com','010-6275-4138');
	
	INSERT INTO T_WEDDING_REGISTRYFRIENDS 
	VALUES(T_WEDDING_REGISTRYFRIENDS_SEQ.NEXTVAL,'wastty@naver.com','이성권','seongkwon@gamil.com','010-4315-2710');
	
	
	INSERT INTO T_WEDDING_REGISTRYFRIENDS 
	VALUES(T_WEDDING_REGISTRYFRIENDS_SEQ.NEXTVAL,'ektha920@naver.com','서희현','gm300643@hanmail.com','010-7358-1027');
	
	INSERT INTO T_WEDDING_REGISTRYFRIENDS 
	VALUES(T_WEDDING_REGISTRYFRIENDS_SEQ.NEXTVAL,'ektha920@naver.com','양기열','ykycome00@gmail.com','010-2708-0663');
	
	INSERT INTO T_WEDDING_REGISTRYFRIENDS 
	VALUES(T_WEDDING_REGISTRYFRIENDS_SEQ.NEXTVAL,'ektha920@naver.com','김태민','xoalszz123@naver.com','010-4339-9307');
	
	INSERT INTO T_WEDDING_REGISTRYFRIENDS 
	VALUES(T_WEDDING_REGISTRYFRIENDS_SEQ.NEXTVAL,'ektha920@naver.com','이지현','wlgus7608@naver.com','010-2586-7608');
	
	INSERT INTO T_WEDDING_REGISTRYFRIENDS 
	VALUES(T_WEDDING_REGISTRYFRIENDS_SEQ.NEXTVAL,'ektha920@naver.com','김정식','zxc7qwe@naver.com','010-9793-4966');
	
	INSERT INTO T_WEDDING_REGISTRYFRIENDS 
	VALUES(T_WEDDING_REGISTRYFRIENDS_SEQ.NEXTVAL,'ektha920@naver.com','송지원','송지원8799@naver.com','010-6256-8799');
	
	INSERT INTO T_WEDDING_REGISTRYFRIENDS 
	VALUES(T_WEDDING_REGISTRYFRIENDS_SEQ.NEXTVAL,'ektha920@naver.com','윤현종','wastty@naver.com','010-9448-5627');
	
	INSERT INTO T_WEDDING_REGISTRYFRIENDS 
	VALUES(T_WEDDING_REGISTRYFRIENDS_SEQ.NEXTVAL,'ektha920@naver.com','안용민','326yongme@naver.com','010-6361-1127');
	
	INSERT INTO T_WEDDING_REGISTRYFRIENDS 
	VALUES(T_WEDDING_REGISTRYFRIENDS_SEQ.NEXTVAL,'ektha920@naver.com','남준호','jun3386@nate.com','010-2822-5541');
	
	INSERT INTO T_WEDDING_REGISTRYFRIENDS 
	VALUES(T_WEDDING_REGISTRYFRIENDS_SEQ.NEXTVAL,'ektha920@naver.com','이상현','mylesh21@naver.com','010-6540-4218');
	
	INSERT INTO T_WEDDING_REGISTRYFRIENDS 
	VALUES(T_WEDDING_REGISTRYFRIENDS_SEQ.NEXTVAL,'ektha920@naver.com','조태환','01062744133@naver.com','010-6275-4138');
	
	INSERT INTO T_WEDDING_REGISTRYFRIENDS 
	VALUES(T_WEDDING_REGISTRYFRIENDS_SEQ.NEXTVAL,'ektha920@naver.com','이성권','seongkwon@gamil.com','010-9448-5627');

