	DROP TABLE T_WEDDING_FAQ PURGE;
	DROP SEQUENCE T_WEDDING_FAQ_SEQ;	
	
	CREATE TABLE  T_WEDDING_FAQ (
		NUM NUMBER(6,0) NOT NULL ENABLE, 
		NAME VARCHAR2(200) NOT NULL ENABLE, 
		EMAIL VARCHAR2(200) NOT NULL ENABLE, 
		PNUM VARCHAR2(200) NOT NULL ENABLE, 
		MESSAGE VARCHAR2(500) NOT NULL ENABLE
	);
   
    SELECT * FROM T_WEDDING_FAQ;
  	 
  	CREATE SEQUENCE T_WEDDING_FAQ_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;

  	ALTER TABLE T_WEDDING_FAQ ADD CONSTRAINT T_WEDDING_FAQ_PK PRIMARY KEY(NUM);
  	
  	INSERT INTO T_WEDDING_FAQ VALUES(T_WEDDING_FAQ_SEQ.NEXTVAL,'둘리','douly@gmail.com','010-3333-3333','레지스트리는 뭔가요?');
  	INSERT INTO T_WEDDING_FAQ VALUES(T_WEDDING_FAQ_SEQ.NEXTVAL,'도우너','downer@naver.com','010-4455-9090','회원가입은 어떻게 하나요?');
  	INSERT INTO T_WEDDING_FAQ VALUES(T_WEDDING_FAQ_SEQ.NEXTVAL,'또치','ttochi@daum.net','010-4567-8989','세일 행사는 있나요?');
  	INSERT INTO T_WEDDING_FAQ VALUES(T_WEDDING_FAQ_SEQ.NEXTVAL,'마이콜','michoal@hotmail.com','010-5677-4321','예식장 예약도 되나요?');
  	INSERT INTO T_WEDDING_FAQ VALUES(T_WEDDING_FAQ_SEQ.NEXTVAL,'바람돌리','windyboy@gmail.com','010-5464-9090','드레스가 너무 예쁜데 예약 할 수 있나요?');