	DROP TABLE T_WEDDING_REGISTRYCART PURGE;
	DROP SEQUENCE T_WEDDING_REGISTRYCART_SEQ;
	
	CREATE TABLE  T_WEDDING_REGISTRYCART(
		NUM NUMBER(6,0) NOT NULL ENABLE, 
		NAME VARCHAR2(100) NOT NULL ENABLE, 
		EMAIL VARCHAR2(200) NOT NULL ENABLE, 
		CATEGORY VARCHAR2(100) NOT NULL ENABLE, 
		PRICE NUMBER(15,0) NOT NULL ENABLE, 
		BUYQUANTITY NUMBER(6,0) NOT NULL ENABLE, 
		TOTAL NUMBER(15,0) NOT NULL ENABLE, 
		PAYCHECK VARCHAR2(50)
   	);

   	SELECT * FROM T_WEDDING_REGISTRYCART;
  	 
	CREATE SEQUENCE T_WEDDING_REGISTRYCART_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;
	
	ALTER TABLE T_WEDDING_REGISTRYCART ADD CONSTRAINT T_WEDDING_REGISTRYCART_PK PRIMARY KEY(NUM);
