	DROP TABLE T_WEDDING_SAVEDPOINT PURGE;
	DROP SEQUENCE T_WEDDING_SAVEDPOINT_SEQ;	

	CREATE TABLE  T_WEDDING_SAVEDPOINT(
		NUM NUMBER(6,0) NOT NULL ENABLE, 
		EMAIL VARCHAR2(200) NOT NULL ENABLE,
		POINT NUMBER(15,0) NOT NULL ENABLE
	);

	SELECT * FROM T_WEDDING_SAVEDPOINT;
  	 
	CREATE SEQUENCE T_WEDDING_SAVEDPOINT_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;
	
	ALTER TABLE T_WEDDING_SAVEDPOINT ADD CONSTRAINT T_WEDDING_SAVEDPOINT_PK PRIMARY KEY(NUM);