	DROP TABLE T_WEDDING_CHECKLIST PURGE;
	DROP SEQUENCE T_WEDDING_CHECKLIST_SEQ;
	
	CREATE TABLE  T_WEDDING_CHECKLIST(
		NUM NUMBER(6,0) NOT NULL ENABLE, 
		EMAIL VARCHAR2(200), 
		LISTDATA VARCHAR2(300)
   	);
   	
   	SELECT * FROM T_WEDDING_CHECKLIST;
  	 
  	CREATE SEQUENCE T_WEDDING_CHECKLIST_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;

  	ALTER TABLE T_WEDDING_CHECKLIST ADD CONSTRAINT T_WEDDING_CHECKLIST_PK PRIMARY KEY(NUM);
  	
  	INSERT INTO T_WEDDING_CHECKLIST VALUES(T_WEDDING_CHECKLIST_SEQ.NEXTVAL, 'wastty@naver.com','val1,val2,val3,val4,val5,val6,val7,val8,val9,val10,val11');