	DROP TABLE T_WEDDING_REGISTRYPRODUCT PURGE;
	DROP SEQUENCE T_WEDDING_REGISTRYPRODUCT_SEQ;
	
	CREATE TABLE  T_WEDDING_REGISTRYPRODUCT(
		NUM NUMBER(6,0) NOT NULL ENABLE, 
		NAME VARCHAR2(100) NOT NULL ENABLE, 
		PRICE NUMBER(15,0) NOT NULL ENABLE, 
		CONTENT VARCHAR2(500) NOT NULL ENABLE, 
		SYSNAME VARCHAR2(300) NOT NULL ENABLE, 
		ORGNAME VARCHAR2(300) NOT NULL ENABLE, 
		QUANTITY NUMBER(6,0) NOT NULL ENABLE, 
		CATEGORY VARCHAR2(100)
   	);
   	
   	SELECT * FROM T_WEDDING_REGISTRYPRODUCT;
  	 
	CREATE SEQUENCE T_WEDDING_REGISTRYPRODUCT_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;
	
	ALTER TABLE T_WEDDING_REGISTRYPRODUCT ADD CONSTRAINT T_WEDDING_REGISTRYPRODUCT_PK PRIMARY KEY(NUM);
	
  	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'엘지드럼세탁기',980000,'풀스테인레스/건조기능','lgtromwasher.jpg','lgtromwasher.jpg',100,'생활가전');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'다이슨청소기',1080000,'무선','dysonvaccum.jpg','dysonvaccum.jpg',100,'생활가전');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'엘지김치냉장고',560000,'일반형','lgrefregerator.jpg','lgrefregerator.jpg',100,'주방가전');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'브라운전동칫솔',150000,'무선','powertoothbrush.jpg','powertoothbrush.jpg',100,'뷰티가전');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'삼성겔럭시탭',300000,'10인치/안드로이드','samsunggalaxytap.jpg','samsunggalaxytap.jpg',100,'스마트가전');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'애플아이패드프로',740000,'9.7인치/iOS 10/128GB','appleipadpro.jpg','appleipadpro.jpg',100,'스마트가전');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'윈도우서피스프로',1500000,'코어/i5/8GB/SSD256GB','windowserpeace.jpg','windowserpeace.jpg',100,'스마트가전');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'한샘식탁',380000,'대리석','dinnigtable.jpg','dinnigtable.jpg',100,'주방가구');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'포트메리온식기세트',270000,'6인용','portmerion.jpg','portmerion.jpg',100,'주방기구');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'플레이스테이션',360000,'500GB','playstation.jpg','playstation.jpg',100,'게임가전');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'Xbox',260000,'1TB','xbox.jpg','xbox.jpg',100,'게임가전');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'Wii',530000,'512MB','wii.jpg','wii.jpg',100,'게임가전');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'필립스전기면도기',210000,'3D','powershaving.jpg','powershaving.jpg',100,'뷰티가전');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'JMW헤어드리어어',80000,'전문가용/3단풍량','JMWhairdryer.jpg','JMWhairdryer_1.jpg',100,'뷰티가전');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'노비타비데',150000,'세정/건조/스테인레스노즐/전자','노비타비데15만세정&건조&스테인레스노들&전자식.jpg','노비타비데15만세정&건조&스테인레스노들&전자식.jpg',100,'생활가전');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'동양식기세척기',250000,'6인용/열풍건조/냉수전용','동양식기세척기25만6인용열풍건조냉수전용.jpg','동양식기세척기25만6인용열풍건조냉수전용.jpg',100,'주방가전');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'드롱기커피메이커',180000,'전자동/분쇄파드커피','드롱기커피메이커18만전자동분쇄파드커피.jpg','드롱기커피메이커18만전자동분쇄파드커피.jpg',100,'주방가전');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'드롱기토스트제빵기',120000,'데우기/해동/빵가루받침대','드롱기토스트제빵기12만데우기해동빵가루받침대.jpg','드롱기토스트제빵기12만데우기해동빵가루받침대.jpg',100,'주방가전');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'리큅식품건조기',120000,'8단트리/발효/온도조절','리큅식품건조기12만8단트리에발효온도조절.jpg','리큅식품건조기12만8단트리에발효온도조절.jpg',100,'주방가전');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'브라더제봉틀',150000,'14가지바느질/수평가마','브라더제봉틀15만14가지바느질&수평가마.jpg','브라더제봉틀15만14가지바느질&수평가마.jpg',100,'생활가전');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'삼성기어S3',400000,'1.3인치/타이젠/OLED','삼성기어S340만1.3인치&타이젠&OLED.jpg','삼성기어S340만1.3인치&타이젠&OLED.jpg',100,'스마트가전');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'삼성도어락',300000,'카드키/번호/태그','삼성도어락30만카드키&번호&태그.jpg','삼성도어락30만카드키&번호&태그.jpg',100,'생활가전');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'삼성파워봇로봇청소기',1000000,'100분사용/충전2시간40분','삼성파워봇로봇청소기100만100분사용충전2시간40분.jpg','삼성파워봇로봇청소기100만100분사용충전2시간40분.jpg',100,'생활가전');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'샤오미스마트체중계',30000,'디지털방식/최대150kg','샤오미스마트체중계3만디지털방식&최대150kg.jpg','샤오미스마트체중계3만디지털방식&최대150kg.jpg',100,'생활가전');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'아일랜드식탁의자',100000,'1인/바의자','아일랜드식탁의자1인&바의자.jpg','아일랜드식탁의자1인&바의자.jpg',100,'주방가구');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'애플워치',600000,'1.7인치/OLED','애플워치60만1.7인치OLED.jpg','애플워치60만1.7인치OLED.jpg',100,'스마트가전');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'엘지디오스식기세척기',600000,'12인용/열풍건조','엘지디오스식기세척기60만12인용열풍건조.jpg','엘지디오스식기세척기60만12인용열풍건조.jpg',100,'주방가전');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'엘지울트라노트북65만',650000,'i3듀얼코어/15인치/8GB/500GB','엘지울트라노트북65만i3듀얼코어&15인치&8GB&500GB.jpg','엘지울트라노트북65만i3듀얼코어&15인치&8GB&500GB.jpg',100,'스마트가전');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'엘지퓨리케어정수기',1200000,'정수냉수/전기분해/살균수/터치식','엘지퓨리케어정수기110만정수냉수전기분해살균수터치식.jpg','엘지퓨리케어정수기110만정수냉수전기분해살균수터치식.jpg',100,'주방가전');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'조셉조셉도마',40000,'미니','조셉조셉도마4만미니.jpg','조셉조셉도마4만미니.jpg',100,'주방기구');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'코렐꽃솜',110000,'4인/3중압축비트렐유리','코렐꽃솜11만4인&3중압축비트렐유리.jpg','코렐꽃솜11만4인&3중압축비트렐유리.jpg',100,'주방기구');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'쿠진아트통구이스핀바베큐',140000,'전기그릴','쿠진아트통구이스핀바베큐14만전기그릴.jpg','쿠진아트통구이스핀바베큐14만전기그릴.jpg',100,'주방가전');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'테팔에이프투터치',50000,'1.5리터/무선','테팔에이프투터치5만1.5리터무선.jpg','테팔에이프투터치5만1.5리터무선.jpg',100,'주방가전');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'테팔프리무브다리미',130000,'수직스팀/스프레이/무선','테팔프리무브다리미13만수직스팀&스프레이&무선.jpg','테팔프리무브다리미13만수직스팀&스프레이&무선.jpg',100,'생활가전');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'포트메리온머그컵',120000,'6인','포트메리온머그컵12만6인.jpg','포트메리온머그컵12만6인.jpg',100,'주방기구');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'포트메리온보타닉가든한수저부부2벌6만',60000,'부부2벌','포트메리온보타닉가든한수저부부2벌6만.jpg','포트메리온보타닉가든한수저부부2벌6만.jpg',100,'주방기구');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'포트메리온완인잔',120000,'6인','포트메리온완인잔12만&6인.jpg','포트메리온완인잔12만&6인.jpg',100,'주방기구');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'포트메리온홈세트9',900000,'10인/도자기','포트메리온홈세트90만10인&도자기.jpg','포트메리온홈세트90만10인&도자기.jpg',100,'주방기구');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'필립스비자퓨어어드밴스드',230000,'피부관리/충전식','필립스비자퓨어어드밴스드23만피부관리&충전식.jpg','필립스비자퓨어어드밴스드23만피부관리&충전식.jpg',100,'뷰티가전');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'필립스아방세',140000,'2리터/버튼/다이얼식','필립스아방세14만2리터버튼다&다이얼식.jpg','필립스아방세14만2리터버튼다&다이얼식.jpg',100,'주방가전');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'필립스튀김기',230000,'800g/1구투입구','필립스튀김기23만800g1구투입구.jpg','필립스튀김기23만800g1구투입구.jpg',100,'주방가전');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'한국도자기홈세트',300000,'8인/본차이나','한국도자기홈세트30만8인&본차이나.jpg','한국도자기홈세트30만8인&본차이나.jpg',100,'주방기구');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'해피콜냄비세트',100000,'알루미늄/편수/양수','해피콜냄비세트10만알루미늄&편수&양수.jpg','해피콜냄비세트10만알루미늄&편수&양수.jpg',100,'주방기구');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'헬켈5스타6종블럭세트',190000,'칼혼합세트','헬켈5스타6종블럭세트19만칼혼합세트.jpg','헬켈5스타6종블럭세트19만칼혼합세트.jpg',100,'주방기구');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'휘슬러압력솥',300000,'3중바닥/분리형손잡이','휘슬러압력솥30만3중바닥&분리형손잡이.jpg','휘슬러압력솥30만3중바닥&분리형손잡이.jpg',100,'주방기구');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'휘슬러팔레르모5종냄비세트',300000,'스테인레스/편수/양수','휘슬러팔레르모5종냄비세트30만스테인레스&편수&양수.jpg','휘슬러팔레르모5종냄비세트30만스테인레스&편수&양수.jpg',100,'주방기구');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'의자2',60000,'1인','의자2.jpg','의자2.jpg',100,'주방가구');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'의자3',100000,'1인','의자3.jpg','의자3.jpg',100,'주방가구');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'의자4',110000,'1인용','의자4.jpg','의자4.jpg',100,'주방가구');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'쿠쿠밥솥',400000,'IH압력솥','rice_cooker.jpg','rice_2.jpg',100,'주방가전');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'삼성전자렌지',80000,'항균세라믹코팅/700W','microwave.jpg','microwave.jpg',100,'주방가전');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'의자1',50000,'1인용','의자1.jpg','의자1.jpg',100,'주방가구');

	INSERT INTO T_WEDDING_REGISTRYPRODUCT 
	VALUES(T_WEDDING_REGISTRYPRODUCT_SEQ.NEXTVAL,'의자5',130000,'1인용','의자5.jpg','의자5.jpg',100,'주방가구');

	